---
deployment:
  tasks:
    - export HOME=/home/nanocomputingict
    - export NPM_CONFIG_PREFIX=$HOME/.npm
    - export PATH="$HOME/.npm/bin:$PATH"
    - npm install
    - npm run build
    - /usr/bin/touch tmp/restart.txt
